#!/bin/bash

remoteCI='ssh -i ./circle/middlemanServer ubuntu@54.187.239.243'

#$remoteCI aws ecr get-login --region us-west-2 | bash
$remoteCI /home/ubuntu/ecs-deploy -c tend-production -n BossService -i 948369953119.dkr.ecr.us-west-2.amazonaws.com/boss:production -t 600
