#!/bin/bash

remoteCI='ssh -i middlemanServer ec2-user@54.187.113.187'
boss=948369953119.dkr.ecr.us-west-2.amazonaws.com/boss:latest
updatePullCmd='git pull'

$remoteCI aws ecr get-login --region us-west-2 | bash
#$remoteCI docker pull $boss
psID=`$remoteCI docker run -d -w="/root/boss" -t $boss `
$remoteCI docker exec -t $psID $updatePullCmd
#run tests here
$remoteCI docker commit --pause=false $psID $boss
$remoteCI docker stop $psID
$remoteCI docker rm $psID
$remoteCI docker push $boss


